# Site settings
title: Public Slack Channels
email: svansintjan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of Public Slack Channels
baseurl: "/public-slack-channels/" # the subpath of your site, e.g. /blog/
url: "http://simonv3.github.io" # the base hostname & protocol for your site
twitter_username: simonv3
github_username:  simonv3

# Build settings
markdown: kramdown
